from foodgram.constants import (INGREDIENT_NAME_MAX_LENGTH,
                                MAX_INGREDIENT_AMOUNT, MIN_AMOUNT,
                                MIN_COOKING_TIME, MIN_INGREDIENT_AMOUNT,
                                RECIPE_NAME_MAX_LENGTH, UNIT_MAX_LENGTH)

NAME_MAX_LENGTH = INGREDIENT_NAME_MAX_LENGTH

__all__ = [
    'NAME_MAX_LENGTH',
    'UNIT_MAX_LENGTH',
    'RECIPE_NAME_MAX_LENGTH',
    'MIN_COOKING_TIME',
    'MIN_AMOUNT',
    'MIN_INGREDIENT_AMOUNT',
    'MAX_INGREDIENT_AMOUNT'
]
