from foodgram.constants import (EMAIL_MAX_LENGTH, USER_NAME_MAX_LENGTH,
                                USERNAME_MAX_LENGTH, USERNAME_REGEX_PATTERN)

NAME_MAX_LENGTH = USER_NAME_MAX_LENGTH

__all__ = [
    'EMAIL_MAX_LENGTH',
    'USERNAME_MAX_LENGTH',
    'NAME_MAX_LENGTH',
    'USERNAME_REGEX_PATTERN',
]
