# API / пагинация
DEFAULT_PAGE_SIZE = 6
PAGE_SIZE_QUERY_PARAM = 'limit'

# Пользователи
EMAIL_MAX_LENGTH = 254
USERNAME_MAX_LENGTH = 150
USER_NAME_MAX_LENGTH = 150
USERNAME_REGEX_PATTERN = r'^[\w.@+-]+$'

# Рецепты / Ингредиенты
INGREDIENT_NAME_MAX_LENGTH = 128
UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256
MIN_COOKING_TIME = 1
MIN_AMOUNT = 1
