# Generated by Django 4.2.14 on 2025-12-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
