# Generated by Django 4.2.14 on 2025-12-02 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(
                '^[\\w.@+-]+$', 'Enter a valid username.')], verbose_name='Username'),
        ),
    ]
